server:
  port: 8766

#数据库的连接配置
spring:
  datasource:
    url: jdbc:mysql://10.11.60.183:3307/hyzg?serverTimezone=CST
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.109.120
  rabbitmq:
    host: 192.168.109.120
    port: 5672
    username: wlkg
    password: 123456
    virtual-host: /wlkg
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 210000ms
        multiplier: 2
      exchange: wlkg.item.exchange
    publisher-confirms: true
